
# Copyright (c) 2022 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Mirror Container Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 5 * * *
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get -y update
    - name: Install Skopeo
      run: sudo apt-get -y install skopeo
    - name: Login to Quay
      uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - name: Mirror Container Images
      run: ./image-mirror.sh quay.io/devfile
